development:
  database: link_short
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: link_short_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
